#Spawn coordinate
spawn:
  world: world
  x: 0
  y: 4.0
  z: 0.0
  Yaw: 0
  Pitch: 0

#Message send to the player with different action
Message:
  Setspawn: "&6Spawn Create"
  TpToSpawn: "&6Teleported to Spawn..."
  TpToSpawnbyAdmin: "&6Teleported to Spawn by an Admin..."

#Custom permission
Permission--tp-player-to-spawn: "hSpawn.SpawnOtherPlayer"

#For the list of every sound, go here : https://dev.bukkit.org/projects/justsound/pages/sound-list
playsound-on-/spawn: true
SoundName: ENTITY_PLAYER_LEVELUP