name: hSpawn
version: '${version}'
main: fr.ht06.hspawn.HSpawn
api-version: '1.20'
author: ht06
commands:
  spawn:
    description: Teleport the player to spawn
    permission: hspawn.spawn

  setspawn:
    description: Create the spawn location
    permission: hspawn.setspawn
    aliases: sspawn

  test:
    description: Test command

  hreload:
    description: reload the config of the plugin hSpawn
    permission: hSpawn.reload
    aliases: hrl

